apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: product-catalog-app
  labels:
    commit: master-6eac8652ffdebb0d59c53f969307fc34b3359d09
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-catalog-app
  template:
    metadata:
      labels:
        app: product-catalog-app
        commit: master-6eac8652ffdebb0d59c53f969307fc34b3359d09
    spec:
      containers:
      - name: product-catalog-app-container
        image: stmsg/alpha-office-product-catalog
        imagePullPolicy: Always
        ports:
        - name: pc-app-port
          containerPort: 80
          protocol: TCP
      imagePullSecrets:
        - name: wercker
---
apiVersion: v1
kind: Service
metadata:
  name: product-catalog-service
  labels:
    app: product-catalog-app
    commit: master-6eac8652ffdebb0d59c53f969307fc34b3359d09
spec:
  ports:
  - port: 30000
    targetPort: 80
  selector:
    app: product-catalog-app
    commit: master-6eac8652ffdebb0d59c53f969307fc34b3359d09
  type: LoadBalancer
---
